### ISSUE TITLE
Migrar a código isomorfo que funcione tanto en node como en browser

### ISSUE THREAD

**Issue by Tsur** [Tsur/node-rae#6]

**Comment by juanarbol** [comment]
Yo puedo ayudar con la implementación de Babel para esto.

**Comment by Tsur** [comment]
Me parece genial, la idea es básicamente que la API sea compatible tanto en nodejs como en el browser. En teoría con los últimos cambios en inestable debería ser ya compatible, pero no lo he probado en browser aún. Gracias.

**Comment by Tsur** [comment]
dado que la API no es publica, un comportamiento isomorfico requeriria CORS, lo cual no esta en nuestra mano poder modificar, se cierra por tanto la tarea, aunque para facilitar la tarea a quienes lo necesitan se incluye el servidor de ejemplo que puedan usar de proxy para exponer su propia RAE API
