### ISSUE TITLE
Mejorar la Calidad del proyecto

### ISSUE THREAD

**Issue by Tsur** [Tsur/node-rae#8]
Integración Continua, Análisis de Dependencias, Análisis de Cobertura, Linting ... etc

**Comment by juanarbol** [comment]
¿puede ser más preciso en qué se debe mejorar?

**Comment by Tsur** [comment]
Hola @juanarbol, gracias por tu interés en el proyecto.

No puedo dedicar demasiado tiempo al proyecto, todos estos issues son "recordatorios personales" para saber en lo que debo trabajar en líneas generales, así que disculpa por lo vago de las descripciones. 

El [milestone](https://github.com/Tsur/node-rae/milestone/1) se encuentra en un estado bastante avanzado. Puedes sincronizarte con la rama `inestable` para ver el progreso actual o probar los últimos cambios ejecutando `npm install rae@next -g`. 

Respondiendo a tu pregunta de forma más especifica, me refiero a incluir eslint. En esta misma línea también podríamos usar flow o typescript para tipado estático, pero por ahora lo descarto. Tal vez en una próxima versión.  

También se ha incluido un bundle analyzer para generar un reporte de dependencias. Tenemos soporte de commitizen para normalizar el formato de los mensajes en los commits. Finalmente los procesos de lint, build, & test están automatizados en integración continua con travisci y los reportes de cobertura igualmente accesibles desde coveralls.

En principio esta tarea esta ya terminada, pero si quieres ayudar, tenemos una cobertura actual del 78%, estaría bien incrementar la cobertura. Gracias!
