### ISSUE TITLE
Muy pesado para ser un módulo

### ISSUE THREAD

**Issue by Bestulo** [tsur/node-rae#9]
En la mañana instalé este módulo para ponerle funcionalidad de diccionario a mi bot. Agradezco mucho que lo hayas creado, pues sé que yo no habría sido capaz de hacerlo. Lamentablemente no pude usarlo porque tenía un par de problemas. El primero es que es extremadamente pesado. Cuando me mandaba un error de "not a valid word", por ejemplo, me llevaba a `line 1 character 277831` o algo así. 

Me puse a investigar y resulta que, como sospeché, lo hiciste en es6+ y lo babelizaste a un Nodejs primitivo. Está bien por la compatibilidad, por si alguien usa un nodejs anterior (aunque deberían actualizar), pero babel incluyó en el mismo paquete, gracias a su polyfill, o quizás fue por el webpack, TODOS los módulos requeridos tanto por el webpack como por el cliente normal, etc. Es decir, adentro de `lib/index.js` tienes cientos y cientos de líneas de caracteres chinos (sin exagerar, te pongo screenshot).

![image](https://user-images.githubusercontent.com/23301025/34266733-b0edf802-e650-11e7-86f8-90aba8e26167.png)

Creí al principio que todo este módulo de `iconv-lite` era esencial para la funcionalidad de `node-rae`, pero me puse a revisar y al final decidí que iba a hacer una versión sin esos módulos para purificar un poco el ambiente. Terminé con una sola página de 173 líneas de ES6 aceptable para node 9.2.1 (que es el que uso). Puedes verlo [aquí](https://github.com/Bestulo/rae-lite/blob/master/index.js), no es nada del otro mundo. No tiene la función de cli, pero tampoco planeo usarla.

Adicionalmente, tenías otro problema: la detección de isAWord en [src/helpers/utils](https://github.com/tsur/node-rae/blob/estable/src/helpers/utils.js) utiliza un regex que excluye las tildes y la ñ (y me lanzaba error cuando buscaba caño, lo que ahora puede hacer bien con el nuevo regex). Puedes encontrar el nuevo [aquí](https://github.com/Bestulo/rae-lite/blob/master/index.js#L29), también bastante simple.

En general me pareció que aunque el módulo está muy bien, y te aplaudo por la maestría con la que resolviste los retos de la RAE, deberías tomar en consideración al usuario común que quiera integrarlo en un paquete más grande sin bajarse unos cuantos megabytes de módulos (incluyendo el webpack de tu demo, que no sé qué hace en el paquete de npm) que nunca va a usar incrustados en el index de algo que se podía resolver en 170 líneas. Buenas tardes, muchas gracias por todo.

edit: Mi amigo sugiere que si vas a hacer parsing de Javascript, te revises este módulo que te la pone más fácil: [eslint/espree](https://github.com/eslint/espree)

**Comment by tsur** [comment]
https://github.com/tsur/node-rae/releases/tag/v1.0.2 https://github.com/tsur/node-rae/commit/640b0e8b730eae1b1c342e75d2937ac901f61841
